"""
Battle Engine - Digital Twin Stress Testing
Implements the 3-stage 'Hardcore' stress testing workflow.
"""

from typing import Dict, Any, List
from datetime import datetime
from structured_profile_generator import profile_to_prompt_context
from product_catalog import get_product_catalog_text

def run_battle_stress_test(
    profile: Dict[str, Any],
    callModel: callable,
    model_name: str = "gemini",
    status_callback: callable = None
) -> Dict[str, Any]:
    """
    Runs the 3-stage battle stress test.
    
    1. Proposal Generation (Hybrid: Whole Life + Term)
    2. AI Attack (The Adversary)
    3. Reinforcement Learning (Auto-Refining)
    """
    
    product_catalog = get_product_catalog_text()
    profile_context = profile_to_prompt_context(profile)
    
    # ---------------------------------------------------------
    # STAGE 1: PROPOSAL GENERATION (Hybrid Focus)
    # ---------------------------------------------------------
    if status_callback:
        status_callback("Stage 1/3: Generating Hybrid Proposal...")
        
    proposal_prompt = f"""
You are an expert Northwestern Mutual Financial Representative.
Your goal is to create a robust HYBRID financial plan for this client.

{product_catalog}

CLIENT PROFILE:
{profile_context}

INSTRUCTIONS:
Create a comprehensive proposal that specifically combines:
1. **Permanent Life Insurance** (Whole Life/Custom/Advisory) for long-term value.
2. **Term Life Insurance** for immediate, high-volume protection.
3. **Disability/LTC** if applicable.

Focus on 'The Blend' - explain why mixing Term (cheap protection) and Perm (asset class) is superior to 'Buy Term and Invest the Difference'.

STRUCTURE:
## EXECUTIVE SUMMARY
## THE HYBRID STRATEGY (The 'Why')
## RECOMMENDED PRODUCTS
[List specific products and premiums]
## PROJECTED OUTCOMES
"""

    proposal_text = callModel(proposal_prompt, model=model_name, max_tokens=2500)
    
    # ---------------------------------------------------------
    # STAGE 2: AI ATTACK (The Adversary)
    # ---------------------------------------------------------
    if status_callback:
        status_callback("Stage 2/3: Launching AI Adversary Attack...")
        
    attack_prompt = f"""
You are a skeptical, financially savvy 'Digital Twin' of the client, powered by aggressive independent financial AI.
You are extremely critical of insurance-based investments. You believe in 'Buy Term and Invest the Difference' (BTID).

You have just received this proposal from a Northwestern Mutual advisor:

{proposal_text}

YOUR MISSION:
Attack this proposal. Be ruthless. Find every weakness.
Focus on:
1. **Expenses & Commissions**: "Why am I paying high fees when I can buy cheap term?"
2. **Opportunity Cost**: "If I put that Perm premium into the S&P 500, I'd have way more money."
3. **Complexity**: "This is too complicated. Keep it simple."
4. **Liquidity**: "Why lock my money up?"

Output a structured 'Vulnerability Report':

## VULNERABILITY REPORT
### 1. COST INEFFICIENCY
[Attack high premiums]

### 2. INVESTMENT PERFORMANCE
[Attack the internal rate of return vs. market]

### 3. SALES BIAS
[Accuse advisor of commission seeking]

### 4. FATAL FLAWS
[Identify specific weak logic]
"""

    attack_text = callModel(attack_prompt, model=model_name, max_tokens=2000)
    
    # ---------------------------------------------------------
    # STAGE 3: REINFORCEMENT LEARNING (Auto-Refining)
    # ---------------------------------------------------------
    if status_callback:
        status_callback("Stage 3/3: Auto-Refining & Pre-bunking...")
        
    refinement_prompt = f"""
You are the master Financial Representative. You have analyzed the 'Vulnerability Report' generated by the client's AI.

ORIGINAL PROPOSAL:
{proposal_text}

AI ATTACK:
{attack_text}

YOUR TASK:
Rewrite the original proposal to become 'Battle-Hardened'.
You must **PRE-BUNK** the objections. This means answering them *before* the client even asks, weaving the counter-arguments into the main narrative so the AI's attack seems uninformed or outdated.

STRATEGY:
- Acknowledge the 'Buy Term' argument explicitly and dismantle it with math (e.g., "Tax-equivalent yield").
- Address the 'High Fee' myth by explaining net-of-fee performance.
- Frame 'Liquidity' correctly (Cash Value accessibility).

OUTPUT:
A new, final proposal titled "## BATTLE-TESTED FINANCIAL STRATEGY".
It should look like a polished document, but bulletproof against the specific attacks raised.
"""

    refined_proposal_text = callModel(refinement_prompt, model=model_name, max_tokens=3000)
    
    return {
        "timestamp": datetime.now().isoformat(),
        "stage_1_proposal": proposal_text,
        "stage_2_attack": attack_text,
        "stage_3_refined": refined_proposal_text
    }
